#!/usr/bin/env node
/**
 * build-archive.mjs — builds the whole site's issue layer from source files.
 *
 * PUBLISHING AN ISSUE
 * -------------------
 * Add one file: issues/YYYY-MM-DD.md, with front matter at the top:
 *
 *     ---
 *     title: The week the economists disagreed
 *     dek: One line of standfirst, optional.
 *     ---
 *
 *     ## Finance & Consulting
 *     **Lead sentence in bold.** Then the paragraph...
 *
 * Push it. CI runs this script, which renders issue-YYYY-MM-DD.html, rebuilds
 * the archive list and regenerates feed.xml. Nothing else to edit.
 *
 * UNPUBLISHING
 * ------------
 * Add `draft: true` to that issue's front matter and push. The page, the archive
 * row and the feed item all disappear. Remove the line to put it back.
 *
 * LEGACY GOOGLE DOC ISSUES
 * ------------------------
 * issues.json still holds the pre-markdown issues as { "date", "docId" } entries.
 * They keep rendering through issue.html exactly as before, so old links never
 * break. Don't add new entries there — write a markdown file instead.
 *
 * Set GROUP_BY_MONTH = true to break the archive into labelled month sections
 * (archive.html already has .month-label styling waiting for it).
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, unlinkSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { markdownToHtml, frontMatter, plainText } from './markdown.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://sophiastafford.github.io/disequilibrium';
const GROUP_BY_MONTH = false;

const START = '<!-- ARCHIVE:START -->';
const END = '<!-- ARCHIVE:END -->';
const STAMP = '<!-- generated by scripts/build-archive.mjs — edit issues/*.md, not this file -->';

const MONTHS = ['January','February','March','April','May','June',
                'July','August','September','October','November','December'];

const fail = (msg) => { console.error(`\n  build-archive failed: ${msg}\n`); process.exit(1); };
const warn = (msg) => console.warn(`  ! ${msg}`);

const parseDate = (s) => {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(s ?? '')) return null;
  const [y, m, d] = s.split('-').map(Number);
  const dt = new Date(Date.UTC(y, m - 1, d));
  const real = dt.getUTCFullYear() === y && dt.getUTCMonth() === m - 1 && dt.getUTCDate() === d;
  return real ? dt : null;
};

const pretty = (dt) => `${MONTHS[dt.getUTCMonth()]} ${dt.getUTCDate()}, ${dt.getUTCFullYear()}`;
const xml = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const attr = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
                             .replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// ---------------------------------------------------------------- collect

const issues = [];
const seen = new Map();

const claim = (date, where) => {
  if (seen.has(date)) fail(`two issues share the date ${date} — ${seen.get(date)} and ${where}.`);
  seen.set(date, where);
};

// --- markdown issues (the current way) ---

const issuesDir = join(ROOT, 'issues');
if (existsSync(issuesDir)) {
  for (const name of readdirSync(issuesDir).sort()) {
    if (!name.endsWith('.md')) continue;
    const where = `issues/${name}`;

    const dt = parseDate(name.slice(0, -3));
    if (!dt) fail(`${where} isn't named for a real date.\n` +
                  `  Issue files must be named YYYY-MM-DD.md — e.g. issues/2026-09-01.md`);

    const { data, body } = frontMatter(readFileSync(join(issuesDir, name), 'utf8'));
    if (!body.trim()) fail(`${where} has no content below its front matter.`);

    const date = name.slice(0, -3);
    claim(date, where);

    if (data.draft) { warn(`${where} is marked draft — skipping.`); continue; }

    // A title is optional. Without one the issue is headed by its date, which is
    // how every issue before the markdown switch read.
    issues.push({
      kind: 'md', date, dt, source: where,
      title: data.title ? String(data.title) : pretty(dt),
      hasTitle: Boolean(data.title),
      dek: data.dek ? String(data.dek) : '',
      body,
      page: `issue-${date}.html`,
    });
  }
}

// --- legacy Google Doc issues ---

const legacyPath = join(ROOT, 'issues.json');
if (existsSync(legacyPath)) {
  let legacy;
  try {
    legacy = JSON.parse(readFileSync(legacyPath, 'utf8'));
  } catch (e) {
    fail(`could not read issues.json — ${e.message}`);
  }
  if (!Array.isArray(legacy)) fail('issues.json must be a JSON array.');

  for (const [i, it] of legacy.entries()) {
    const where = `issues.json entry ${i + 1}`;
    if (!it || typeof it !== 'object') fail(`${where} is not an object.`);

    const dt = parseDate(it.date);
    if (!dt) fail(`${where} has date "${it.date}" — must be a real YYYY-MM-DD date.`);

    // A Google Doc ID, not a full URL — a pasted URL is the likeliest mistake here.
    if (!/^[A-Za-z0-9_-]{20,}$/.test(it.docId ?? ''))
      fail(`${where} (${it.date}) has docId "${it.docId}".\n` +
           `  Expected just the ID, e.g. 1qtimJAUQ0So45KuOlEG1lbtRE2K23ezdCk63pRp5nck\n` +
           `  From a Drive URL, that's the part between /document/d/ and /edit.`);

    claim(it.date, where);
    if (it.draft) { warn(`${where} is marked draft — skipping.`); continue; }

    issues.push({
      kind: 'doc', date: it.date, dt, source: where,
      title: pretty(dt), dek: '', docId: it.docId,
      page: `issue.html?doc=${it.docId}&date=${encodeURIComponent(pretty(dt))}`,
    });
  }
}

if (!issues.length) fail('no published issues found — add issues/YYYY-MM-DD.md.');

issues.sort((a, b) => b.dt - a.dt);

// ---------------------------------------------------------- issue pages

const templatePath = join(ROOT, 'templates', 'issue.template.html');
if (!existsSync(templatePath)) fail('templates/issue.template.html is missing.');
const template = readFileSync(templatePath, 'utf8');

const generated = new Set();
let pagesWritten = 0;

issues.forEach((it, idx) => {
  if (it.kind !== 'md') return;

  const newer = issues[idx - 1];   // list is newest-first
  const older = issues[idx + 1];

  const link = (o, label) =>
    `<a href="${attr(o.page)}">${label}</a>`;

  const pager = (newer || older)
    ? `<nav class="pager">\n` +
      (older ? `      ${link(older, '← ' + pretty(older.dt))}\n` : '') +
      `      <span class="spacer"></span>\n` +
      (newer ? `      ${link(newer, pretty(newer.dt) + ' →')}\n` : '') +
      `    </nav>`
    : '';

  const description = (it.dek || plainText(it.body)).slice(0, 300).trim();

  // Replacement values go through a function so that a "$" in an issue — a dollar
  // figure, say — is never read as a regex substitution pattern like $& or $'.
  // The page itself shows the masthead and the dated subtitle line, matching the
  // Doc-era issues. `title` and `dek` from the front matter are metadata only:
  // they drive the share preview and the feed, and appear nowhere on the page.
  const fill = {
    title: attr(it.title),
    dateLabel: attr(pretty(it.dt)),
    ogTitle: attr(it.hasTitle ? `${it.title} — Disequilibrium` : `Disequilibrium — ${pretty(it.dt)}`),
    description: attr(description),
    canonical: attr(`${SITE}/${it.page}`),
    pager,
    content: markdownToHtml(it.body),
  };

  const missing = [];
  const html = template.replace(/\{\{(\w+)\}\}/g, (match, key) => {
    if (!(key in fill)) { missing.push(key); return match; }
    return fill[key];
  });
  if (missing.length)
    fail(`templates/issue.template.html uses unknown placeholder(s): ${[...new Set(missing)].join(', ')}`);

  const out = html.replace('</head>', `${STAMP}\n</head>`);
  const path = join(ROOT, it.page);
  generated.add(it.page);

  if (!existsSync(path) || readFileSync(path, 'utf8') !== out) {
    writeFileSync(path, out);
    pagesWritten++;
    console.log(`  wrote ${it.page}`);
  }
});

// Remove pages whose source markdown was deleted or flipped to draft. Only files
// carrying our stamp are touched, so hand-written pages are never collateral.
for (const name of readdirSync(ROOT)) {
  if (!/^issue-\d{4}-\d{2}-\d{2}\.html$/.test(name)) continue;
  if (generated.has(name)) continue;
  if (!readFileSync(join(ROOT, name), 'utf8').includes(STAMP)) continue;
  unlinkSync(join(ROOT, name));
  console.log(`  removed ${name} (no longer published)`);
}

// ------------------------------------------------------------- archive

const row = (it, pad) =>
  `${pad}<a class="issue" href="${attr(it.page)}">` +
  `<span class="date serif">${pretty(it.dt)}</span>` +
  `<span class="meta"><span class="label">Read issue</span>` +
  `<span class="arrow">→</span></span></a>`;

let block;
if (GROUP_BY_MONTH) {
  const groups = [];
  for (const it of issues) {
    const key = `${it.dt.getUTCFullYear()}-${it.dt.getUTCMonth()}`;
    if (!groups.length || groups.at(-1).key !== key)
      groups.push({ key, label: `${MONTHS[it.dt.getUTCMonth()]} ${it.dt.getUTCFullYear()}`, rows: [] });
    groups.at(-1).rows.push(it);
  }
  block = groups.map(g =>
    `      <div class="month">\n` +
    `        <p class="month-label">${g.label}</p>\n` +
    g.rows.map(it => row(it, '        ')).join('\n') + '\n' +
    `      </div>`
  ).join('\n\n');
} else {
  block = `      <div class="month">\n` +
          issues.map(it => row(it, '        ')).join('\n') + '\n' +
          `      </div>`;
}

const archivePath = join(ROOT, 'archive.html');
const archive = readFileSync(archivePath, 'utf8');
const a = archive.indexOf(START);
const b = archive.indexOf(END);
if (a === -1 || b === -1 || b < a)
  fail(`archive.html is missing the ${START} / ${END} markers around the issue list.`);

const nextArchive = archive.slice(0, a + START.length) + '\n' + block + '\n' + '      ' + archive.slice(b);
if (nextArchive !== archive) {
  writeFileSync(archivePath, nextArchive);
  console.log(`  archive.html updated — ${issues.length} issues, newest ${issues[0].date}`);
} else {
  console.log(`  archive.html already current — ${issues.length} issues`);
}

// ---------------------------------------------------------------- feed
// Markdown issues ship their full text, so an RSS-to-email service (Buttondown,
// Kit, Mailchimp) can mail the actual issue rather than a bare link.

const items = issues.map((it) => {
  const url = `${SITE}/${it.page}`;
  const title = it.kind === 'md'
    ? `${it.title} — ${pretty(it.dt)}`
    : `Disequilibrium — ${pretty(it.dt)}`;
  const summary = it.kind === 'md'
    ? (it.dek || plainText(it.body).slice(0, 400) + '…')
    : `Disequilibrium for ${pretty(it.dt)}.`;
  const full = it.kind === 'md'
    ? `\n      <content:encoded><![CDATA[${markdownToHtml(it.body)}]]></content:encoded>`
    : '';
  return `    <item>
      <title>${xml(title)}</title>
      <link>${xml(url)}</link>
      <guid isPermaLink="true">${xml(url)}</guid>
      <pubDate>${it.dt.toUTCString()}</pubDate>
      <description>${xml(summary)}</description>${full}
    </item>`;
}).join('\n');

const feed = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>Disequilibrium</title>
    <link>${SITE}/</link>
    <description>A weekly newsletter on how AI is changing the entry-level job market.</description>
    <language>en-us</language>
    <lastBuildDate>${issues[0].dt.toUTCString()}</lastBuildDate>
    <atom:link href="${SITE}/feed.xml" rel="self" type="application/rss+xml"/>
${items}
  </channel>
</rss>
`;

const feedPath = join(ROOT, 'feed.xml');
if (!existsSync(feedPath) || readFileSync(feedPath, 'utf8') !== feed) {
  writeFileSync(feedPath, feed);
  console.log('  feed.xml updated');
} else {
  console.log('  feed.xml already current');
}

const mdCount = issues.filter(i => i.kind === 'md').length;
console.log(`\n  done — ${issues.length} issues (${mdCount} markdown, ${issues.length - mdCount} legacy), ${pagesWritten} page(s) written\n`);
